sudo: false

language: python

addons:

matrix:
  include:
    - python: "3.10"

install:
  - make develop

before_script:

script:
  - make test

notifications:
  email:
    security-foundations@lyft.com
